### ISSUE TITLE
page de profil utilisateur

### ISSUE THREAD

**Issue by nsobczak** [nsobczak/e-shopping#4]
Assigné à : Nicolas & Vincent

**Comment by nsobczak** [comment]
**TODO:**
- [ ] Gérer la connexion de l'utilisateur
- [ ] Upload une image
- [ ] Mettre à jour l'image dans la bdd
- [ ] Gérer la modification de mot de passe
